export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const LOGOUT = "LOGOUT";
export const REQUEST_LOGIN_SUCCESS = "REQUEST_LOGIN_SUCCESS";
export const REQUEST_LOGIN_FAILURE = "REQUEST_LOGIN_FAILURE";

export const FETCH_ALL_USERS = "FETCH_ALL_USERS";

export const FETCH_ALL_POST = "FETCH_ALL_POST";
