// Auth type
export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const REQUEST_LOGIN_SUCCESS = "REQUEST_LOGIN_SUCCESS";
export const REQUEST_LOGIN_FAILURE = "REQUEST_LOGIN_FAILURE";
export const GET_USER ="GET_USER"
export const LOGOUT = "LOGOUT";
export const SIGNIN = "SIGHIN";

export const VIEW_NOTIFICATION = 'VIEW_NOTIFICATION'

export const FETCH_ALL_USERS = "FETCH_ALL_USERS";

export const FETCH_ALL_POST = "FETCH_ALL_POST";
